id: I4BC05509
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-4882
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 10:52:11.092896+00:00
last_modified: 2023-09-26 10:52:11.092905+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13019
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13019
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྭགས་པོ་ཐར་རྒྱན།
  languages:
  - bo
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9784133898841191
  ocr_word_median_confidence_index: 0.9997756
bases:
  I1KG13099:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13099
      total_pages: 368
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13099.txt
    statistics:
      ocr_word_median_confidence_index: 0.9997756
      ocr_word_mean_confidence_index: 0.9784133898841191
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
